version: '3.7'

services:
  web:
    build: . # -t blenzi/websocket
    command: python main.py
#    command: gunicorn -b 0.0.0.0 main:run_app()
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - "8050:8050"
